---
- hosts: webservers
  remote_user: root
  roles:
    - webservers

  tasks:
  - name: initialize deploy root
    deploy_helper:
      path: "{{ backend_path }}"
      state: present

  - name: ensure release present
    file:
      path: "{{ deploy_helper.new_release_path }}"
      state: directory

  - name: mark deploy as unfinished
    file:
      path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
      state: touch

  - name: upload assets
    unarchive:
      src: ../backend/_build/prod/rel/keeb/releases/{{ backend_version }}/keeb.tar.gz
      dest: "{{ deploy_helper.new_release_path }}"

  - name: stop existing server
    systemd:
      name: keeb
      state: stopped

  - name: start new server
    systemd:
      name: keeb
      state: started

  - name: finalize deploy
    deploy_helper:
      path: "{{ backend_path }}"
      release: "{{ deploy_helper.new_release }}"
      state: finalize
      clean: True
